# Generated by Django 2.2.6 on 2019-10-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dadosx', models.CharField(max_length=255)),
                ('dadosy', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=50)),
            ],
        ),
    ]
